---
# See https://github.com/jvautier/project-cli
fullname: jvautier/versions-cli
description: Fetch github, pipy or hashicorp product versions
tags:
  - api
  - cli
github:
  has_issues: true
  has_projects: false
  has_wiki: false
